[provider]
cluster = "devnet"  # Change to "mainnet-beta" when deploying to mainnet
wallet = "~/.config/solana/id.json"

[programs.devnet]
up_only = "1q6XfXMucUSmdYqjDjkbWt8ZYFm4ox7d6fT4CfHrt2T"

[programs.localnet]
up_only = "71SrXrVtxh3efZgxQRidBJeVZY1PKaTY6mcRRomVcuy8"

[programs.mainnet]
up_only = "YOUR_MAINNET_PROGRAM_ID_HERE"  # Replace this when deploying to mainnet

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 60000 tests/**/*.ts"

[workspace]
members = [
    "programs/up_only"
]

[clusters]
localnet = "http://localhost:8899"
devnet = "https://api.devnet.solana.com"
mainnet = "https://api.mainnet-beta.solana.com"

[build]
skip-lint = false
arch = "bpf"
